name: build
on:
  workflow_dispatch:
  pull_request:
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: yarn install
      - run: yarn build


      - uses: actions/upload-artifact@v4
        with:
          name: nightly-release
          path: |
            * 
